version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: test.Dockerfile
    ports:
      - 80:8080
    environment:
      - CGO_ENABLED=0
    volumes:
      - ./:/app
    networks:
      - se214
    depends_on:
      - migrate
  migrate:
    image: migrate/migrate
    networks:
      - se214
    volumes:
      - ./db/migration:/migrations
    command: -database "mysql://root:example@tcp(db:3306)/se214?query" -path /migrations up
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: se214
    networks:
      - se214
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
networks:
  se214: