version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    environment:
      - CGO_ENABLED=0
    networks:
      - se214
    depends_on:
      - db
      - adminer
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: se214
    ports:
      - "3306:3306"
    networks:
      - se214
    volumes:
      - se214-mysql-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - se214
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docs:/docs:ro"
    ports:
      - "80:80"
    depends_on:
      - server
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - se214
  migrate:
    image: migrate/migrate
    networks:
      - se214
    volumes:
      - ./db/migration:/migrations
    entrypoint: migrate -database "mysql://root:example@tcp(db:3306)/se214?query" -path /migrations up
networks:
  se214:
volumes:
  se214-mysql-db: