version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    environment:
      - CGO_ENABLED=0
    networks:
      - se214
    depends_on:
      - db
      - adminer
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: se214
    ports:
      - "3306:3306"
    networks:
      - se214
    volumes:
      - se214-mysql-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - se214
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docs:/usr/share/nginx/html/:ro"
    ports:
      - "80:80"
    depends_on:
      - server
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - se214
networks:
  se214:
volumes:
  se214-mysql-db: