version: "3.8"
services:
  server:
    image: dinhlockt02/se214-be
    networks:
      - se214
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - example.env
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: se214
    ports:
      - "3306:3306"
    networks:
      - se214
    volumes:
      - se214-mysql-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - se214
    depends_on:
      - db
  nginx:
    image: dinhlockt02/se214-proxy
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - se214
  migrate-up:
    image: dinhlockt02/se214-migrate
    networks:
      - se214
    entrypoint: migrate -database "mysql://root:example@tcp(db:3306)/se214?query" -path /migrations up
    depends_on:
      db:
        condition: service_healthy
networks:
  se214:
volumes:
  se214-mysql-db:
