CREATE TABLE IF NOT EXISTS DauSach (
    MaDauSach VARCHAR(255) PRIMARY KEY,
    TenDauSach VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CT_TacGia (
    MaDauSach VARCHAR(255),
    MaTacGia VARCHAR(255),
    CONSTRAINT CT_TacGia_PK PRIMARY KEY (MaDauSach, MaTacGia),
    CONSTRAINT CT_TacGia_FK_DauSach FOREIGN KEY(MaDauSach) REFERENCES DauSach(MaDauSach),
    CONSTRAINT CT_TacGia_FK_TacGia FOREIGN KEY(MaTacGia) REFERENCES TacGia(MaTacGia)
);

CREATE TABLE IF NOT EXISTS CT_TheLoai (
    MaDauSach VARCHAR(255),
    MaTheLoai VARCHAR(255),
    CONSTRAINT CT_TheLoai_PK PRIMARY KEY (MaDauSach, MaTheLoai),
    CONSTRAINT CT_TheLoai_FK_DauSach FOREIGN KEY(MaDauSach) REFERENCES DauSach(MaDauSach),
    CONSTRAINT CT_TheLoai_FK_TheLoai FOREIGN KEY(MaTheLoai) REFERENCES TheLoai(MaTheLoai)
)

