// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireimpl

import (
	"daijoubuteam.xyz/se214-library-management/config"
	"daijoubuteam.xyz/se214-library-management/core/repository"
	"daijoubuteam.xyz/se214-library-management/core/service"
	"daijoubuteam.xyz/se214-library-management/infrastructure/mysql"
	"daijoubuteam.xyz/se214-library-management/infrastructure/service"
	"daijoubuteam.xyz/se214-library-management/usecase/auth"
	"daijoubuteam.xyz/se214-library-management/usecase/thu_thu"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitThuThuUsecase(db *sqlx.DB) thuthu.ThuThuUsecase {
	bcryptPasswordHasher := service.NewBcryptPasswordHasher()
	thuThuRepository := mysql.NewThuThuRepository(db)
	thamSoRepository := mysql.NewThamSoRepository(db)
	thuThuService := thuthu.NewThuThuService(bcryptPasswordHasher, thuThuRepository, thamSoRepository)
	return thuThuService
}

func InitAuthUsecase(db *sqlx.DB) auth.AuthUsecase {
	bcryptPasswordHasher := service.NewBcryptPasswordHasher()
	thuThuRepository := mysql.NewThuThuRepository(db)
	thamSoRepository := mysql.NewThamSoRepository(db)
	thuThuService := thuthu.NewThuThuService(bcryptPasswordHasher, thuThuRepository, thamSoRepository)
	jwtConfig := config.GetJwtConfig()
	jwtTokenServiceImpl := service.NewJwtTokenServiceImpl(jwtConfig)
	authService := auth.NewAuthService(thuThuService, bcryptPasswordHasher, jwtTokenServiceImpl)
	return authService
}

// wire.go:

var PasswordHasherSet = wire.NewSet(wire.Bind(new(coreservice.PasswordHasher), new(*service.BcryptPasswordHasher)), service.NewBcryptPasswordHasher)

var JwtTokenServiceSet = wire.NewSet(wire.Bind(new(coreservice.JwtTokenService), new(*service.JwtTokenServiceImpl)), service.NewJwtTokenServiceImpl, config.GetJwtConfig)

var ThuThuRepositorySet = wire.NewSet(wire.Bind(new(repository.ThuThuRepository), new(*mysql.ThuThuRepository)), mysql.NewThuThuRepository)

var ThamSoRepositorySet = wire.NewSet(wire.Bind(new(repository.ThamSoRepository), new(*mysql.ThamSoRepository)), mysql.NewThamSoRepository)

var ThuThuUsecaseSet = wire.NewSet(wire.Bind(new(thuthu.ThuThuUsecase), new(*thuthu.ThuThuService)), thuthu.NewThuThuService, PasswordHasherSet, ThuThuRepositorySet, ThamSoRepositorySet)

var AuthUsecaseSet = wire.NewSet(wire.Bind(new(auth.AuthUsecase), new(*auth.AuthService)), auth.NewAuthService, ThuThuUsecaseSet, JwtTokenServiceSet)
