name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dinhlockt02/se214-be:latest
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push proxy
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dinhlockt02/se214-proxy:latest
          platforms: linux/amd64,linux/arm64
          file: ./proxy.Dockerfile
      -
        name: Build and push migration
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dinhlockt02/se214-migrate:latest
          platforms: linux/amd64,linux/arm64
          file: ./migrate.Dockerfile